/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import BD.guardar;
import BD.guardarPotting;
import java.util.ArrayList;
import BD.inspe;
import jdk.nashorn.internal.parser.Token;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author jluis
 */
public class HistorialPottingChips extends javax.swing.JInternalFrame {

    /**
     * Creates new form Historial
     */
    public HistorialPottingChips() {
        initComponents();
//        setLocationRelativeTo(null);
        ListarHistorial();
        Bdetalles.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Historial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BuscaPN = new javax.swing.JTextField();
        Bdetalles = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        Historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P/N", "Trabajo No.", "Lote", "Procedimiento", "Fecha Ingreso", "Cantidad Ingreso", "Fecha Salida", "Cantidad Salida", "Notas", "Realizado Por"
            }
        ));
        Historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistorialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Historial);

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel1.setText("P/N");

        BuscaPN.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        BuscaPN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscaPNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscaPNKeyTyped(evt);
            }
        });

        Bdetalles.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        Bdetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        Bdetalles.setText("Detalles");
        Bdetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuscaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(Bdetalles)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BuscaPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdetalles))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscaPNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscaPNKeyTyped
      
    }//GEN-LAST:event_BuscaPNKeyTyped

    private void BuscaPNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscaPNKeyReleased
       ListarHistorial();
    }//GEN-LAST:event_BuscaPNKeyReleased

    private void BdetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdetallesActionPerformed
             
            int filaseleccionada = Historial.getSelectedRow();
            int no = (int) Historial.getValueAt(filaseleccionada, 0);
            DetallesPottingChips h= new DetallesPottingChips(no);
            h.setVisible(true);
             
    }//GEN-LAST:event_BdetallesActionPerformed

    private void HistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialMouseClicked
       Bdetalles.setEnabled(true);
    }//GEN-LAST:event_HistorialMouseClicked

    private void ListarHistorial(){
    
        ArrayList<inspe> result = guardarPotting.ListarPNPottingChips(BuscaPN.getText());
        RecargarTabla(result);    
    }
    private void RecargarTabla(ArrayList<inspe> list) {
        
        Object[][] datos = new Object[list.size()][10];
        int i = 0;
        for (inspe m : list)
        {    
            datos[i][0] = m.getNo();
            datos[i][1] = m.getPN();
            datos[i][2] = m.getTrabajo();
            datos[i][3] = m.getLote();
            datos[i][4] = m.getProceso();
            datos[i][5] = m.getFechain();
            datos[i][6] = m.getCantidadIn();
            datos[i][7] = m.getFechaout();
            datos[i][8] = m.getCantidadOut();
            datos[i][9] = m.getNotas();
            i++;
        }       
        Historial.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "No.","P/N","Trabajo","Lote","Proceso","Fecha Ingreso","Cantidad Ingreso","Fecha Salida","Cantidad Salida","Notas"
                }) {
                     @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialPottingChips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialPottingChips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialPottingChips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialPottingChips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialPottingChips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bdetalles;
    private javax.swing.JTextField BuscaPN;
    private javax.swing.JTable Historial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
